name: Application Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build | Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: reniciuspagotto/ci-cd-reusable-composite/.github/composite-actions/checkout@main
        with:
          fetch-depth: 1
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x 
      
      - name: Dotnet Build
        run: |
          dotnet restore
          dotnet build

      - name: Dotnet Test
        run: dotnet test

  security-scan:
    name: Security
    needs: build
    uses: reniciuspagotto/ci-cd-reusable-composite/.github/workflows/security.yml@main
    with:
      image_name: apiservice:latest
      solution_file_path: ./AzDotNetWebApi.sln
    secrets: inherit